/*
 * File: app/view/AddExpense.js
 *
 * This file was generated by Sencha Architect version 3.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('ExpenseTracker.view.AddExpense', {
    extend: 'Ext.Container',
    alias: 'widget.addexpense',

    config: {
        items: [
            {
                xtype: 'titlebar',
                docked: 'top',
                ui: 'light',
                title: 'Add Expense',
                items: [
                    {
                        xtype: 'button',
                        handler: function(button, e) {
                            Ext.Viewport.setActiveItem({
                                xtype : 'tabpanel',
                                activeItem : 1
                            });
                        },
                        text: 'Back'
                    }
                ]
            },
            {
                xtype: 'formpanel',
                height: '100%',
                itemId: 'addexpenseform',
                items: [
                    {
                        xtype: 'hiddenfield',
                        itemId: 'id',
                        name: 'id'
                    },
                    {
                        xtype: 'textfield',
                        itemId: 'name',
                        label: 'Name',
                        labelWrap: true,
                        name: 'name',
                        required: true,
                        placeHolder: 'Enter Name'
                    },
                    {
                        xtype: 'textfield',
                        itemId: 'notes',
                        label: 'Notes',
                        labelWrap: true,
                        name: 'notes',
                        placeHolder: 'Enter Notes'
                    },
                    {
                        xtype: 'selectfield',
                        itemId: 'category',
                        label: 'Category',
                        labelWrap: true,
                        name: 'category',
                        required: true,
                        displayField: 'name',
                        store: 'Categories',
                        valueField: 'id'
                    },
                    {
                        xtype: 'textfield',
                        itemId: 'price',
                        label: 'Price',
                        labelWrap: true,
                        name: 'price',
                        required: true,
                        placeHolder: 'Enter Price'
                    },
                    {
                        xtype: 'datepickerfield',
                        label: 'Date',
                        name: 'date',
                        required: true,
                        placeHolder: 'dd/mm/yyyy',
                        dateFormat: 'd/m/Y',
                        picker: {
                            useTitles: true,
                            slotOrder: [
                                'day',
                                'month',
                                'year'
                            ],
                            yearFrom: 2013
                        }
                    },
                    {
                        xtype: 'button',
                        handler: function(button, e) {
                            var formObj = button.up('formpanel');
                            var formData = formObj.getValues();
                            var formTypeAdd = true;
                            if(formData.id === '') {//add form

                                var expense = Ext.create('ExpenseTracker.model.Expense',{
                                    name: formData.name,
                                    notes: formData.notes,
                                    categoryid: formData.category,
                                    price: formData.price,
                                    date: formData.date

                                });

                            } else {//edit form

                                formTypeAdd = false;
                                var expense = Ext.getStore('Expenses').getById(formData.id);
                                expense.set('name', formData.name);
                                expense.set('notes', formData.notes);
                                expense.set('categoryid', formData.category);
                                expense.set('price', formData.price);
                                expense.set('date', formData.date);
                            }

                            var errs = expense.validate();
                            var msg = '';

                            if (!errs.isValid()) {
                                errs.each(function (err) {
                                    msg += err.getField() + ' : ' + err.getMessage() + '<br/>';
                                });

                                Ext.Msg.alert('ERROR', msg);

                            } else {
                                if(formTypeAdd){
                                    Ext.getStore('Expenses').add(expense);
                                }
                                Ext.getStore('Expenses').sync();
                                Ext.Msg.alert('SUCCESS', 'Expense saved successfully');

                                Ext.Viewport.setActiveItem({
                                    xtype : 'tabpanel',
                                    activeItem : 1
                                });
                            }
                        },
                        itemId: 'add',
                        style: 'position:relative;float:left;width:50%',
                        text: 'Save'
                    },
                    {
                        xtype: 'button',
                        handler: function(button, e) {

                            var formObj = button.up('formpanel');
                            var formData = formObj.getValues();

                            var id = formData.id;
                            record = Ext.getStore('Expenses').getById(id);

                            if(record === null || record === undefined){
                                Ext.Msg.alert('Error', 'Expense remove fails');
                            }

                            //record.phantom = true;

                            Ext.Msg.confirm('DELETE CONFIRM', 'Are you sure you want to delete?', function (btn) {
                                if (btn === 'yes') {
                                    Ext.getStore('Expenses').remove(record);
                                    Ext.getStore('Expenses').sync();
                                    Ext.Msg.alert('SUCCESS', 'Expense removed successfully');

                                    Ext.Viewport.setActiveItem({
                                        xtype : 'tabpanel',
                                        activeItem : 1
                                    });

                                } // switch
                            }); // confirm()

                        },
                        hidden: true,
                        itemId: 'delete',
                        style: 'position:relative;width:50%',
                        text: 'delete'
                    }
                ]
            }
        ]
    }

});