/*
 * File: app.js
 *
 * This file was generated by Sencha Architect version 3.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Sencha Touch 2.3.x library, under independent license.
 * License of Sencha Architect does not include license for Sencha Touch 2.3.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

// @require @packageOverrides
Ext.Loader.setConfig({

});


Ext.application({
    models: [
        'Category',
        'Expense'
    ],
    stores: [
        'Categories',
        'Expenses'
    ],
    views: [
        'TabPanel',
        'AddCategory',
        'AddExpense'
    ],
    requires: [
        'ExpenseTracker.util.Config',
        'Ext.dataview.List',
        'Ext.Button',
        'Ext.TitleBar',
        'Ext.form.Panel',
        'Ext.field.Select',
        'Ext.Label',
        'Ext.Container',
        'Ext.Component',
        'Ext.field.DatePicker',
        'Ext.MessageBox',
        'Ext.field.Hidden',
        'Ext.field.Text',
        'Ext.data.identifier.Sequential'
    ],
    controllers: [
        'Controller'
    ],
    name: 'ExpenseTracker',

    launch: function() {

        Ext.create('ExpenseTracker.view.TabPanel', {fullscreen: true});
    }

});
